"""empty message

Revision ID: cdb50b12a2ce
Revises: 7b8fd78eada3
Create Date: 2022-11-30 22:06:55.399151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb50b12a2ce'
down_revision = '7b8fd78eada3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_data')
    with op.batch_alter_table('event_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venueBookingFee', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_db', schema=None) as batch_op:
        batch_op.drop_column('venueBookingFee')

    op.create_table('event_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('eventNumber', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('eventName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('eventEntryFee', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('maximumOccupancy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdBy', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('eventDate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('eventStartTime', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('eventEndTime', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('venueNumber', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('venueName', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('venueLocation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('graduationLevel', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='event_data_pkey'),
    sa.UniqueConstraint('eventNumber', name='event_data_eventNumber_key')
    )
    # ### end Alembic commands ###
