"""empty message

Revision ID: ce802fb0b05f
Revises: 9468b3f526da
Create Date: 2022-12-01 22:52:31.991234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce802fb0b05f'
down_revision = '9468b3f526da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numberAttending', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_db', schema=None) as batch_op:
        batch_op.drop_column('numberAttending')

    # ### end Alembic commands ###
